name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: theanh0804.duckdns.org
          username: theanh
          password: theanh2004
          script: |
            cd /home/theanh/GIT/SWD391-FoodyGo-FE/
            sudo chmod -R 777 .
            git fetch --all
            git clean -df
            git reset --hard origin/main
            npm install
            npm run build
            sudo rm -rf /var/www/html/foodygo/*
            sudo cp -R /home/theanh/GIT/SWD391-FoodyGo-FE/dist/* /var/www/html/foodygo
            sudo systemctl restart nginx